name: teenmind.co.uk
favicon: null
layout_spectrum: 0.09233614429831505
typography_spectrum: 0.9023327580653131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.00810133502818644
  lightness: 0.059719466138631105
  saturation: 0.531006119446829
  rhythmicContrast: 0.052071216981858015
purpose: []
